# Generated by Django 4.0.5 on 2022-08-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Download',
            field=models.ImageField(blank=True, upload_to='blogArtwork'),
        ),
    ]
