# Generated by Django 4.0.5 on 2022-09-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='Download',
        ),
        migrations.AddField(
            model_name='blogs',
            name='file',
            field=models.FileField(blank=True, upload_to='blogImages'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
