# Generated by Django 4.0.5 on 2022-09-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogs_download_blogs_file_alter_blogs_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='file',
            new_name='fileupload',
        ),
    ]
